---
- name: Deploy Ansible development server
  hosts: all
  become: true

  vars:
    # username for private automation hub for EE or to password protected registry
    pah_user: "USERNAME"
    # password for private automation hub for EE or to password protected registry
    pah_pass: "PASSWORD"
    # username for development server
    username: "ansible"
    # port for web server access
    dev_server_port: 443
    # folder to create to deploy ssl certs
    certandkeyfolder: "/certs/"
    # name of certificate, delete if using self-signed
    cert_location: "CERT.cer"
    # name of key, delete if using self-signed
    key_location: "KEY.key"
    # specific image to pull to development server and assign in ansible-navigator.yml
    ansible_image: "registry.redhat.io/ansible-automation-platform23/ee-supported-rhel8:latest"

  roles:
    - shadowman_dev_server
